<a href="https://colab.research.google.com/github/Darshanbreddy/python/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")

hello


In [2]:
name=input("ENTER NAME: ")
print("name is ", name)

ENTER NAME: Darshan
name is  Darshan


In [3]:
num1=input("enter number")
num2=input("enter second number")
print(num1+num2)

enter number2
enter second number3
23


Type Casting

In [4]:
num1=int(input("enter number: "))
num2=int(input("enter second number: "))
print(num1+num2)

enter number: 2
enter second number: 3
5


Assignment and Equality operator

In [5]:
# Assignment operator (=)
x = 5
y = 10
print("x =", x)
print("y =", y)

# Equality operator (==)
print("Is x equal to y?", x == y)

z = 5
print("Is x equal to z?", x == z)

x = 5
y = 10
Is x equal to y? False
Is x equal to z? True


In [6]:
# Assignment operator (=)
a = 10
b = 10

# Equality operator (==) with if statement
if a == b:
    print("a is equal to b")
else:
    print("a is not equal to b")

# Another example with different values
c = 5
d = 15

if c == d:
    print("c is equal to d")
else:
    print("c is not equal to d")

a is equal to b
c is not equal to d


In [7]:
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

if num2 != 0:
    print(f"{num1} + {num2} = {num1 + num2}")
    print(f"{num1} - {num2} = {num1 - num2}")
    print(f"{num1} * {num2} = {num1 * num2}")
    print(f"{num1} / {num2} = {num1 / num2}")
    print(f"{num1} % {num2} = {num1 % num2}")
else:
    print("Cannot perform division or modulo by zero.")

Enter the first number: 2
Enter the second number: 3
2.0 + 3.0 = 5.0
2.0 - 3.0 = -1.0
2.0 * 3.0 = 6.0
2.0 / 3.0 = 0.6666666666666666
2.0 % 3.0 = 2.0


In [8]:
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
operation = input("Enter operation (+, -, *, /, %): ")

if operation == '+':
    print(f"{num1} + {num2} = {num1 + num2}")
elif operation == '-':
    print(f"{num1} - {num2} = {num1 - num2}")
elif operation == '*':
    print(f"{num1} * {num2} = {num1 * num2}")
elif operation == '/':
    if num2 != 0:
        print(f"{num1} / {num2} = {num1 / num2}")
    else:
        print("Error: Division by zero!")
elif operation == '%':
    if num2 != 0:
        print(f"{num1} % {num2} = {num1 % num2}")
    else:
        print("Error: Modulo by zero!")
else:
    print("Invalid operation.")

Enter first number: 10
Enter second number: 2
Enter operation (+, -, *, /, %): +
10.0 + 2.0 = 12.0


### Lists

Lists are a built-in data type in Python that are used to store collections of items. They are ordered, mutable (changeable), and allow duplicate values. You can create a list using square brackets `[]`.

In [9]:
# Creating a list
my_list = [1, 2, 3, 4, 5]
print(my_list)

# Lists can contain different data types
mixed_list = [1, "hello", True, 3.14]
print(mixed_list)

[1, 2, 3, 4, 5]
[1, 'hello', True, 3.14]


Here are some common functions and methods used with lists:

*   **`len()`**: Returns the number of items in a list.
*   **`append()`**: Adds an item to the end of the list.
*   **`insert()`**: Inserts an item at a specified index.
*   **`remove()`**: Removes the first occurrence of a specified value.
*   **`pop()`**: Removes and returns the item at a specified index (or the last item if no index is specified).
*   **`index()`**: Returns the index of the first occurrence of a specified value.
*   **`count()`**: Returns the number of times a specified value appears in the list.
*   **`sort()`**: Sorts the list in ascending order.
*   **`reverse()`**: Reverses the order of the list.

In [10]:
my_list = [1, 2, 3, 4, 5]

# len()
print("Length of the list:", len(my_list))

# append()
my_list.append(6)
print("After append(6):", my_list)

# insert()
my_list.insert(1, 1.5)
print("After insert(1, 1.5):", my_list)

# remove()
my_list.remove(3)
print("After remove(3):", my_list)

# pop()
popped_item = my_list.pop(2)
print("Popped item at index 2:", popped_item)
print("List after pop(2):", my_list)

# index()
print("Index of 4:", my_list.index(4))

# count()
my_list.append(4)
print("List after appending 4:", my_list)
print("Count of 4:", my_list.count(4))

# sort()
unsorted_list = [5, 2, 8, 1, 4]
unsorted_list.sort()
print("After sort():", unsorted_list)

# reverse()
unsorted_list.reverse()
print("After reverse():", unsorted_list)

Length of the list: 5
After append(6): [1, 2, 3, 4, 5, 6]
After insert(1, 1.5): [1, 1.5, 2, 3, 4, 5, 6]
After remove(3): [1, 1.5, 2, 4, 5, 6]
Popped item at index 2: 2
List after pop(2): [1, 1.5, 4, 5, 6]
Index of 4: 2
List after appending 4: [1, 1.5, 4, 5, 6, 4]
Count of 4: 2
After sort(): [1, 2, 4, 5, 8]
After reverse(): [8, 5, 4, 2, 1]


### Arrays

In Python, the term "array" can refer to different things. The built-in `array` module provides a way to create arrays that are more memory-efficient than lists when you need to store a large number of elements of the same data type. However, for most data science and numerical tasks, the `numpy` library's arrays (ndarrays) are more commonly used and offer a wide range of functions for numerical operations.

Let's look at `numpy` arrays as they are more prevalent in data analysis. You'll typically import numpy as `np`.

In [11]:
import numpy as np

# Creating a numpy array
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

# Creating an array of a specific data type
int_array = np.array([1, 2, 3], dtype='int32')
print(int_array)

[1 2 3 4 5]
[1 2 3]


NumPy arrays have many attributes and methods. Here are a few:

*   **`shape`**: Returns a tuple representing the dimensions of the array.
*   **`dtype`**: Returns the data type of the elements in the array.
*   **`reshape()`**: Gives a new shape to an array without changing its data.
*   **Mathematical operations**: NumPy arrays support element-wise mathematical operations (+, -, \*, /, etc.).
*   **Aggregate functions**: `sum()`, `mean()`, `max()`, `min()`, etc.

In [12]:
import numpy as np

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", my_array)

# shape
print("Shape of the array:", my_array.shape)

# dtype
print("Data type of the array:", my_array.dtype)

# reshape()
reshaped_array = my_array.reshape(3, 2)
print("Reshaped array:\n", reshaped_array)

# Mathematical operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print("Addition of arrays:", array1 + array2)

# Aggregate functions
print("Sum of array1:", array1.sum())
print("Mean of array2:", array2.mean())

Original array:
 [[1 2 3]
 [4 5 6]]
Shape of the array: (2, 3)
Data type of the array: int64
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
Addition of arrays: [5 7 9]
Sum of array1: 6
Mean of array2: 5.0


This is just an introduction. Both lists and NumPy arrays have many more functionalities. The choice between using a list and a NumPy array depends on your specific needs. Lists are more general-purpose, while NumPy arrays are optimized for numerical operations.

### For Loops

A `for` loop is used for iterating over a sequence (like a list, tuple, string, or range) or other iterable objects. It executes a block of code for each item in the sequence.

In [13]:
# Example of a for loop with a list
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
  print(fruit)

# Example of a for loop with a range
for i in range(5):
  print(i)

apple
banana
cherry
0
1
2
3
4


### While Loops

A `while` loop is used to execute a block of code repeatedly as long as a condition is true.

In [14]:
# Example of a while loop
count = 0
while count < 5:
  print(count)
  count += 1

0
1
2
3
4


Both loops can also use `break` to exit the loop and `continue` to skip the current iteration.

In [15]:
# Example of using break in a for loop
for i in range(10):
  if i == 5:
    break
  print(i)

# Example of using continue in a while loop
count = 0
while count < 10:
  count += 1
  if count % 2 == 0:
    continue
  print(count)

0
1
2
3
4
1
3
5
7
9


Let's define a function called `calculate` that will perform the calculator operations. This function will take three arguments: the first number, the second number, and the operation as a string.

In [16]:
def calculate(num1, num2, operation):
  """Performs a calculation based on the provided numbers and operation."""
  if operation == '+':
    return num1 + num2
  elif operation == '-':
    return num1 - num2
  elif operation == '*':
    return num1 * num2
  elif operation == '/':
    if num2 == 0:
      return "Error: Cannot divide by zero!"
    return num1 / num2
  elif operation == '%':
    if num2 == 0:
      return "Error: Cannot perform modulo by zero!"
    return num1 % num2
  else:
    return "Invalid operation."

# Example of how to use the function:
result = calculate(10, 5, '+')
print(f"10 + 5 = {result}")

result = calculate(20, 4, '/')
print(f"20 / 4 = {result}")

result = calculate(7, 0, '/')
print(f"7 / 0 = {result}")

10 + 5 = 15
20 / 4 = 5.0
7 / 0 = Error: Cannot divide by zero!


**Explanation:**

*   We define the function `calculate` that accepts `num1`, `num2`, and `operation` as parameters.
*   Inside the function, we use `if-elif-else` statements to check the value of the `operation` parameter.
*   Based on the operation, the corresponding arithmetic calculation is performed.
*   For division and modulo, we include a check to prevent division by zero.
*   The function returns the result of the calculation or an error message if the operation is invalid or division by zero occurs.
*   We then show examples of how to call the function with different numbers and operations and print the results.

Day 2 begins from here
